### ISSUE TITLE
Handling line segments properly

### ISSUE THREAD

**Issue by Jaimies** [Chemaclass/EdifactParser#18]
Currently, `LIN` (Line item) segments are not implemented, but that is not the problem.

The thing is that the segments related to `LIN` segments only make sense within the context of their line item. For example

```
LIN+1++9783898307529:EN'
QTY+21:5'
PRI+AAA:27.5'
LIN+2++390787706322:UP'
QTY+23:1'
PRI+AAA:10.87'
``` 

Here, the QTY (Quantity) and PRI (Price) segments only have meaning in relation to their LIN (Line item), so if we just group them together with each other as shown below, the meaning will be lost.

```
"LIN" => [
    1 => LINLineItem(...),
    2 => LINLineItem(...),
],

"QTY" => [
    21 => QTYQuantity(...),
   // 
    23 => QTYQuantity(...),
],
....
```

What we need is to group line items and their attributes together, for example

```
"LIN" => [
    1 => [
        LINLineItem(...),
        QTYQuantity(...),
        PRIPrice(...),
    ],
    2 => [
        LINLineItem(...),
        QTYQuantity(...),
        PRIPrice(...),
    ],
],
```

That will require a bit of refactoring, but I can implement it easily

**Comment by Chemaclass** [comment]
@Jaimies all yours 😃

**Comment by Jaimies** [comment]
With #23 merged, this issue can now be closed.
