### ISSUE TITLE
Should use a 3-letter segment tag instead of the class name

### ISSUE THREAD

**Issue by Jaimies** [Chemaclass/EdifactParser#19]
`SegmentInterface::tag()` is supposed to return `A three-character alphanumeric code that identifies the segment.`, but the implementations all return their `self::class`. 

I can easily fix that, just need approval.

**Comment by Chemaclass** [comment]
Oh, nice catch. I think it shouldn't be any issue using the `3 alphanumeric code` instead of the `class name`, so feel free to create a PR applying this change on all segments.

**Comment by Jaimies** [comment]
Check out pull request #21

**Comment by Chemaclass** [comment]
Done
