### ISSUE TITLE
Changing the class names of the segments to not duplicate the segment tag

### ISSUE THREAD

**Issue by Jaimies** [Chemaclass/EdifactParser#22]
Since we are already returning the actual value of the tag in `SegmentInterface::tag()`, I don't think it makes all that much sense to include the 3-letter code in the name of segment classes, i.e. we can use `NameAndAddress` as the class name instead of `NADNameAddress`.

**Comment by Jaimies** [comment]
Again, pretty easy to implement, just need the approval

**Comment by Chemaclass** [comment]
The original idea of including the 3-letter code in all segment classes was to easily identify the `segment-tag` associated to a particular `class-name`. But now that you mentioned that, maybe it doesn't make that much sense, and we could do what you proposed. 

Feel free to do a PR, so we can evaluate how does it look like, and luckily we merge it if we both like it more with this change.

**Comment by Jaimies** [comment]
I'll try a bit later, for now working on line items

**Comment by Jaimies** [comment]
After having worked a bit with the library, I actually find it handy to have the 3-letter-code in the names of segment classes.

So I guess we can close this issue.
