### ISSUE TITLE
Storing line item data outside of groupedSegments

### ISSUE THREAD

**Issue by Jaimies** [Chemaclass/EdifactParser#27]
Currently, line item data (LIN segments, and the ones related to them, like QTY and PRI) is being stored together with normal data in `gruopedSegments`.

However, the line items data does not follow the structure of normal grouped segments:

```
// normal segments:

[
    ...
    'RFF' => [
        'ADE' => RFFReference(...),
        'PD' => RFFReference(...),
    ],
    ...
]

// line item data

[
    ...
    'LIN' => [
        '1' => [
            'LIN' => [ '1' => LINLineItem(...)], 
            'QTY' => ['21' => QTYQuantity(...), ... ],
            ...
        ],
    ],
    ...
]
```
Basically, regular segments are structured like `Tag > SubID > Segment`, while line items follow `Tag  = 'LIN' > SubID > Tag > SubID`, which does not make enough sense.

What we could do instead is have all the line item data under a separate field in `TransactionMessage`, let's say `lineItems`. And the structure might look like this:

```
TransactionMessage(
    groupedSegments => [...],
    lineItems => [
         '1' => [
              'LIN' => [ '1' => LINLineItem(...)], 
              'QTY' => ['21' => QTYQuantity(...), ... ],
              ...
        ],
    ]
)
```

What do you think?

**Comment by Chemaclass** [comment]
That's a nice idea. Btw, feel free to create PR's whenever you have a good idea like this one. You can always open an issue to discuss and share your ideas before, but you don't have to ask for "permission" always. You can create the PR and explain it in the "PR Description" the idea behind, which is usually good 😄

**Comment by Jaimies** [comment]
#28 handles this
