### ISSUE TITLE
Releasing a new version of the library with the recently-added features

### ISSUE THREAD

**Issue by Jaimies** [Chemaclass/EdifactParser#29]
The plan is to improve the handling of unknown segments first (I'm working on it) and then release a new version of the library that contains all the newly-added features.

I'm pretty sure I can even make the release on my own, though I'm not sure how it's done.

**Comment by Chemaclass** [comment]
Whenever you @Jaimies consider it worth a new release (especially after all the work you've done), feel free to create a new release. If you have never done it, don't worry, it's pretty easy. Try from here: https://github.com/Chemaclass/EdifactParser/releases

### 1) Click "Draft a new release"
<img width="1052" alt="Screenshot 2022-11-09 at 00 18 13" src="https://user-images.githubusercontent.com/5256287/200696786-5724d474-17bd-4da1-b4eb-4a713ef1fe65.png">

### 2) Create a new Tag 
<img width="837" alt="Screenshot 2022-11-09 at 00 21 43" src="https://user-images.githubusercontent.com/5256287/200697212-530a36ef-7b12-4c6a-8500-064a13f2153e.png">

### 3) You can use the same tag name for the version name (eg `3.1.0`) 
<img width="533" alt="Screenshot 2022-11-09 at 00 22 15" src="https://user-images.githubusercontent.com/5256287/200697279-51647117-9e01-4a44-b97f-52576ad2c0f0.png">

### 4) Click `Generate Release Notes` to generate the full release text
<img width="1225" alt="Screenshot 2022-11-09 at 00 19 50" src="https://user-images.githubusercontent.com/5256287/200696953-4b80945a-e99a-446b-921b-179bca5e0858.png">

### 5) That's all. Set as `latest release` and publish it 🥳 
<img width="916" alt="Screenshot 2022-11-09 at 00 22 57" src="https://user-images.githubusercontent.com/5256287/200697352-d50071a7-bb0c-4bc3-a869-3877d09c7747.png">

> **Note**: Let me know if something is unclear or you see something different or any other issue, so I can help you.

**Comment by Chemaclass** [comment]
@Jaimies really nice 👌 https://github.com/Chemaclass/EdifactParser/releases/tag/4.0.0
